### ISSUE TITLE
Syntax highlighting Page crash

### ISSUE THREAD

**Issue by bthaile** [onflow/developer-portal#968]
https://developers.flow.com/nodes/node-operation/monitoring-nodes
This markdown can not be rendered. There is an error on the server parsing the syntax highlighting. 
We updated to newest version of `"prism-react-renderer": "^1.3.5",`

Server logs:
```
2023-03-03T15:47:52.256 app[35d47368] sea [info] TypeError: Cannot read properties of undefined (reading 'length')

2023-03-03T15:47:52.256 app[35d47368] sea [info] at matchGrammar (/app/node_modules/prism-react-renderer/prism/index.cjs.js:720:34)

2023-03-03T15:47:52.256 app[35d47368] sea [info] at Object.tokenize (/app/node_modules/prism-react-renderer/prism/index.cjs.js:471:4)

2023-03-03T15:47:52.256 app[35d47368] sea [info] at Highlight.tokenize (/app/node_modules/prism-react-renderer/dist/index.cjs.js:309:39)

2023-03-03T15:47:52.256 app[35d47368] sea [info] at Highlight.render (/app/node_modules/prism-react-renderer/dist/index.cjs.js:327:52)

2023-03-03T15:47:52.256 app[35d47368] sea [info] at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:231)

2023-03-03T15:47:52.256 app[35d47368] sea [info] at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)

2023-03-03T15:47:52.256 app[35d47368] sea [info] at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)

2023-03-03T15:47:52.256 app[35d47368] sea [info] at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)

2023-03-03T15:47:52.256 app[35d47368] sea [info] at exports.renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)

2023-03-03T15:47:52.256 app[35d47368] sea [info] at handleRequest (/app/build/index.js:14207:49)

2023-03-03T15:47:52.256 app[35d47368] sea [info] at handleDocumentRequest (/app/node_modules/@remix-run/server-runtime/dist/server.js:395:18)
```

**Comment by bthaile** [comment]
Markdown syntax issue, not a dev portal issue. closing
